# Generated by Django 6.0.5 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('farmacia_responsable', 'Farmacia responsable'), ('supervisor', 'Supervisor'), ('externo', 'Externo')], default='farmacia_responsable', max_length=32),
        ),
    ]
